REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_user_role(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.finalize_sale(jsonb, numeric, numeric, numeric) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.delete_sale(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.delete_sale(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.delete_product(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.delete_expired_batch(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.add_stock(uuid, integer, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.remove_stock(uuid, integer) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.get_user_role(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_sale(jsonb, numeric, numeric, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_sale(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_sale(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_product(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_expired_batch(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.add_stock(uuid, integer, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.remove_stock(uuid, integer) TO authenticated;